Lesson2
kkazlov/webix-jet-start pull request #2
Opened 2021-10-04 08:06 UTC by kkazlov

2021-10-04 17:49 UTC, olimed commented on sources/views/contacts-form.js
> +		};
comboStatuses и comboCountries очень похожи, лучше создай функцию, которая будет создавать эти элементы

2021-10-04 17:49 UTC, olimed commented on sources/views/contacts-list.js
> +			$$("mainForm").clear();
логичнее это перенести в класс с формой на urlChange()

2021-10-04 17:49 UTC, olimed commented on sources/views/contacts-list.js
> +			list.unselectAll();
необязательно, ведь записей нет в листе

2021-10-04 17:49 UTC, olimed commented on sources/views/dataConstr.js
> +								});
сделай функцию отдельную

2021-10-04 17:49 UTC, olimed commented on sources/views/top.js
> +				}
оставь вариант с `{_(obj.value)` и добавь лучше значения в файлы с переводом

2021-10-04 19:01 UTC, HelgaListopad requested changes

2021-10-04 19:01 UTC, HelgaListopad commented on sources/views/contacts-form.js
> +		if (contactsID) {
Если параметра нет, стоит очистить форму
```js
else view.clear()
```
Причина - если руками удалить параметр из урла, то в форме останутся данные, в то время как getParam вернёт undefined

2021-10-04 19:01 UTC, HelgaListopad commented on sources/views/contacts-list.js
> +	refreshList() {
А зачем менять селект всегда?
Достаточно делать это
- когда мы удалили выбранную запись
- когда мы удалили все записи

В остальных случаях нет смысла менять всё

2021-10-04 19:01 UTC, HelgaListopad commented on sources/views/contacts-list.js
> +			data: contactsCollection,
Желательно перенести загрузку/синхронизацию в init

2021-10-04 19:01 UTC, HelgaListopad commented on sources/views/contacts-list.js
> +		});
Можно cначала задать событие, потом вызвать select - и оно сработает без нужды отдельно вызывать `setParam`

2021-10-04 19:01 UTC, HelgaListopad commented on sources/views/dataConstr.js
> +								});
Всю вот эту часть с перекрёстными обновлениями коллекций я бы предложила удалить
Это сложно, и это редко нужно на реальных данных

Если у тебя задействованы две или более коллекции для отображения в одном компоненте, проще было бы не подгонять данные, отслеживая все изменения, а в момент отрисовки (`template`) попытаться обратиться за нужным значением к коллекциям.

Пример темплейта, который сработает: https://snippet.webix.com/q93q75hl
Одно условие: если данные приходят не сразу, после их загрузки для листа надо вызвать перерисовку

2021-10-04 19:01 UTC, HelgaListopad commented on sources/models/dataCollections.js
> +		},
Я не рекомендую жёстко связывать данные из всех коллекций таким образом.
См. мой комментарий с примером для `sources/views/dataConstr.js`

2021-10-05 04:19 UTC, kkazlov commented on sources/views/contacts-form.js
> +		if (contactsID) {
done

2021-10-05 04:21 UTC, kkazlov commented on sources/views/contacts-list.js
> +			$$("mainForm").clear();
done

2021-10-05 04:26 UTC, kkazlov commented on sources/views/contacts-list.js
> +	refreshList() {
Не совсем понял в чем ошибка. Метод refreshList() вызывается только при удалении записи. Или нужно код метода перенести в хэндлер удаления?

2021-10-05 04:27 UTC, kkazlov commented on sources/views/contacts-list.js
> +			list.unselectAll();
done

2021-10-05 04:30 UTC, kkazlov commented on sources/views/contacts-list.js
> +		});
done

2021-10-05 04:41 UTC, kkazlov commented on sources/views/contacts-list.js
> +			data: contactsCollection,
done

2021-10-05 05:45 UTC, kkazlov commented on sources/views/dataConstr.js
> +								});
Этот код удалил и переделал связь коллекций

2021-10-05 05:46 UTC, kkazlov commented on sources/views/contacts-form.js
> +		};
done

2021-10-05 05:47 UTC, kkazlov commented on sources/views/dataConstr.js
> +								});
Ох и какой же прекрасный способ. Огромнейшее тебе спасибо! Исправил

2021-10-05 05:47 UTC, kkazlov commented on sources/models/dataCollections.js
> +		},
done

2021-10-05 06:25 UTC, kkazlov commented on sources/views/top.js
> +				}
done

2021-10-05 07:00 UTC, olimed approved these changes

2021-10-05 08:44 UTC, HelgaListopad requested changes

2021-10-05 08:44 UTC, HelgaListopad commented on sources/views/contacts-list.js
> +					Status: statusesCollection.data.order[rndStatus] || "empty",
Для Country и Status ты же вроде больше нигде не учитываешь это "empty", я не права? 
Можно вместо него выставлять null или пустую строку и не держать заведомо несуществующее значение

2021-10-05 08:44 UTC, HelgaListopad commented on sources/views/contacts-list.js
> +	refreshList() {
Да, но сейчас каждый раз, когда ты удаляешь _любую_ запись, у тебя меняется селект. Даже если удаляется одна запись, а селект стоял совсем на другой.
При удалении нужно сделать проверку, а надо ли сообще что-то менять

2021-10-05 08:53 UTC, kkazlov commented on sources/views/contacts-list.js
> +					Status: statusesCollection.data.order[rndStatus] || "empty",
done

2021-10-05 09:05 UTC, kkazlov commented on sources/views/contacts-list.js
> +	refreshList() {
Понял, исправил.

2021-10-05 09:09 UTC, HelgaListopad approved these changes

2021-10-05 09:12 UTC, merged